// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "=(:E#[M*sWi*P-ue@GWJ":
            case "ghost":return img`
........................
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.....fffc1111111f.......
...fc111cd1111111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
